### ISSUE TITLE
Race condition when creating directories in parallel

### ISSUE THREAD

**Issue by shkuznetsov** [jrajav/mkpath#1]
If you parallelise directories creation you can be easily caught by a race condition. Imagine 2 parallel processes A and B:
* A checks folder /foo -- it doesn't exist
* B checks folder /foo -- it doesn't exist
* A creates folder /foo -- it succedes
* B tries to create folder /foo -- it fails with EEXIST exception, which is propagated to the consumer

I've made a fix and will attach a pull request soon, please consider merging it.

**Comment by jrajav** [comment]
I don't think mkpath should have to care if it's being called in parallel, but I do agree that EEXIST should not result in the exception propagating, whatever caused it to happen - mkpath's purpose is to create the folders and that happened.

Thanks!

**Comment by jrajav** [comment]
Closed by #2

**Comment by shkuznetsov** [comment]
No, it didn't happen! If thread (1) creates /foo/bar/baz while thread (2)
creates /foo/bar/sol -- the latter will not be created. Give it a think.

Weird that you think mkpath shouldn't care about parallel execution
scenario, given that it operates in highly asynchronous environment, such
as node. Kind of tells the story.

All the best!

**Comment by jrajav** [comment]
Oh, hm. Let me take a second look at this.

**Comment by shkuznetsov** [comment]
Look:

(1) /foo exists?
(2) /foo exists?
(1) /foo doesn't exist, creating!
(2) /foo doesn't exist, creating!
(1) /foo created!
(2) CRASH! Whoops... (as a result neither of subdirs this process was
trying to create were created)

**Comment by jrajav** [comment]
I think I just didn't make it very clear that I was actually agreeing with you! I meant "it happened" as in, when we get EEXIST the folder creation at that dirpath level has happened and we should continue upwards instead of allowing the exception to propagate. Thus why I merged your PR.

I don't think mkpath should have to care if it's being called in parallel to the extent of checking for externally-imposed race conditions is all I meant. It should definitely be internally consistent.

**Comment by jrajav** [comment]
Closing due to #2 merged. Please let me know if you think there's still an issue though.

**Comment by shkuznetsov** [comment]
Yes sorry that probably was a misunderstanding on my part!
